services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: beam_flow_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Phoenix configuration
      - PHX_HOST=localhost
      - PORT=4000
      - SECRET_KEY_BASE=dLAVzlH9ECigQQUG+zUQXw9QBBjY7+Kn1569mJA7j3oFDLsT/o3SLtm/rdvOc5b1
      # Database configuration
      - DATABASE_URL=ecto://postgres:postgres@db/beam_flow_dev
      - TEST_DATABASE_URL=ecto://postgres:postgres@db/beam_flow_test
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - build_cache:/app/_build
      - deps_cache:/app/deps
      - node_modules_cache:/app/assets/node_modules
    command: >
      sh -c "
        mix deps.get &&
        mix compile &&
        mix phx.server
      "
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: beam_flow_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beam_flow_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./scripts/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  build_cache:
  deps_cache:
  node_modules_cache: