FROM elixir:1.18-alpine

# Install build dependencies
RUN apk add --no-cache build-base git nodejs npm inotify-tools postgresql-client

# Create app directory
WORKDIR /app

# Install hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set development ENV
ENV MIX_ENV=dev
ENV PHX_SERVER=true

# The container will mount the local directory
# so we don't need to copy files here

EXPOSE 4000

CMD ["mix", "phx.server"]